<?php

namespace App\Controller\Admin;

use App\Entity\Film;
use App\Entity\Review;
use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * Class DashboardController
 * @package App\Controller\Admin
 * @IsGranted("ROLE_USER")
 */
class DashboardController extends AbstractDashboardController
{

    /**
     * @Route("/admin", name="admin")
     * @IsGranted("ROLE_USER")
     */
    public function index(): Response
    {
        //return parent::index();
        return $this->render('admin/index.html.twig', [
            'films' => $this->getDoctrine()->getRepository( Film::class)->findAll()
        ]);
    }

    public function configureActions(): Actions
    {

        return parent::configureActions()
            ->update(Crud::PAGE_INDEX, Action::NEW, function (Action $action){
                return $action->setLabel('Añadir %entity_label_singular%');
            });
    }

    public function configureCrud(): Crud
    {
        return
            parent::configureCrud()
                //->overrideTemplate('page/content', 'admin/index.html.twig')
                //->overrideTemplate('label/null', 'admin/index.html.twig')
        ; // TODO: Change the autogenerated stub
    }

    public function configureDashboard(): Dashboard
    {
        return Dashboard::new()
            ->setTitle('Miguel Cruz Demo');

    }

    public function configureMenuItems(): iterable
    {
        yield MenuItem::linktoDashboard('Dashboard', 'fa fa-home');

        yield MenuItem::section('Peliculas');
        yield MenuItem::linkToCrud('Peliculas', 'fa fa-film', Film::class);
        yield MenuItem::linkToCrud('Críticas', 'fa fa-bullhorn', Review::class);


        yield MenuItem::section('Seguridad');
        yield MenuItem::linkToCrud('Usuarios','fas fa-user', User::class );


        // yield MenuItem::linkToCrud('The Label', 'fas fa-list', EntityClass::class);
    }

    public function configureFields(string $pageName): iterable
    {

    }

}
