<?php

namespace App\Controller\Admin;

use App\Entity\Film;
use App\Form\ActorType;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\FormField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class FilmCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Film::class;
    }

    public function configureActions(Actions $actions): Actions
    {
        return parent::configureActions(
            $actions
                ->setPermission(Action::EDIT, "ROLE_ADMIN"))
                ->setPermission(Action::DELETE, "ROLE_ADMIN")
                ->update(Crud::PAGE_INDEX, Action::EDIT, function (Action $action){
                    return $action->setLabel('Editar');
                })
                ->update(Crud::PAGE_INDEX, Action::DELETE, function (Action $action){
                    return $action->setLabel('Eliminar');
                })
                ->add(Crud::PAGE_INDEX, Action::DETAIL)
                ->update(Crud::PAGE_INDEX, Action::DETAIL, function (Action $action){
                    return $action->setLabel('Detalle');
                })
            ;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return parent::configureCrud(
            $crud
                ->setPageTitle(Crud::PAGE_INDEX, 'Peliculas')
                ->setPageTitle(Crud::PAGE_NEW, 'Nueva pelicula')
                ->setPageTitle(Crud::PAGE_DETAIL, 'Detalle')
        ); // TODO: Change the autogenerated stub
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {

        if ($entityInstance->getPremiereAt() > new \DateTimeImmutable()){
            $entityInstance->setIsReleased(false);
        }

        else{
            $entityInstance->setIsReleased(true);
        }

        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
       if (Crud::PAGE_NEW === $pageName || Crud::PAGE_EDIT === $pageName){
           yield FormField::addPanel('Pelicula');
           yield TextField::new('title', 'Titulo');
           yield TextField::new('director', 'Director');
           yield TextField::new('title', 'Titulo');
           yield TextareaField::new('synopsis', 'Sinopsis');
           yield NumberField::new('playingTime', 'Duración (min)');
           yield DateField::new('premiereAt', 'Fecha de estreno');
           yield ArrayField::new('tags', 'Tags');
           yield TextField::new('poster', 'Cartel url');
           yield FormField::addPanel('Actores');
           yield CollectionField::new('actors','Actores')
               ->allowAdd(true)
               ->allowDelete(true)
               ->setEntryType(ActorType::class);

       }

       if (Crud::PAGE_DETAIL === $pageName){
           yield ImageField::new('poster', 'Cartel');
           yield TextField::new('title', 'Titulo');
           yield TextField::new('director', 'Director');
           yield TextField::new('title', 'Titulo');
           yield TextareaField::new('synopsis', 'Sinopsis');
           yield NumberField::new('playingTime', 'Duración');
           yield DateField::new('premiereAt', 'Fecha de estreno');
           yield NumberField::new('ratingCalculate', 'Puntuacion de nuestros usuarios');
           yield ArrayField::new('tags', 'Tags');
           yield CollectionField::new('actors','Actores')->setTemplatePath('admin/film/actors_detail.html.twig');
           yield AssociationField::new('reviews', 'Criticas')->setTemplatePath('admin/film/reviews_detail.html.twig');
       }

       if(Crud::PAGE_INDEX === $pageName){
           yield ImageField::new('poster', 'Cartel');
           yield TextField::new('title', 'Titulo');
           yield TextField::new('director', 'Director');
           yield TextField::new('title', 'Titulo');
           yield TextareaField::new('synopsis', 'Sinopsis');
           yield NumberField::new('playingTime', 'Duración');
           yield NumberField::new('ratingCalculate', 'Puntuación');


       }
    }

}
