<?php

namespace App\Controller\Admin;

use App\Entity\Review;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class ReviewCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Review::class;
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $entityInstance->setUser($this->getUser());

        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }


    public function configureFields(string $pageName): iterable
    {

        if (Crud::PAGE_NEW === $pageName || Crud::PAGE_DETAIL === $pageName){
            yield TextField::new('description', 'Título');
            yield TextareaField::new('content', 'Contenido');
            yield NumberField::new('rating', 'Puntuación');
            yield AssociationField::new('film', 'Pelicula');
        }

        if(Crud::PAGE_INDEX === $pageName){
            yield TextField::new('description', 'Título');
            yield TextareaField::new('content', 'Contenido');
            yield NumberField::new('rating', 'Puntuación');
            yield AssociationField::new('film', 'Pelicula');
        }

    }

}
